spring:
  # 数据库 配置
  datasource:
    url: jdbc:mysql://localhost:3306/ufood?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 发送邮件
  mail:
    host: smtp.qq.com
    # 邮箱账号
    username: 541361418@qq.com
    # 授权码
    password: acknrjylylutbeef
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465 #协议为SMTP是SSL端口号465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

# 端口配置
server:
  port: 8081
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
# mybatis-plus 日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


