# 数据库 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ufood?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# 端口配置
server:
  port: 8082
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
